apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: spring-test
  name: spring-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-test
    spec:
      containers:
      - image: spring-test
        name: spring-test
        imagePullPolicy: Never
        resources: {}
        ports:
          - containerPort: 8012
status: {}
