apiVersion: v1
kind: Service
metadata:
  name:  {{.Values.appLabel}}
  namespace: {{.Values.namespace}}
  labels:
    app:  {{.Values.appLabel}}
spec:
  ports:
  - name: web
    port: {{.Values.service.port}}
    nodePort: {{.Values.service.nodePort}}
    protocol: TCP
  selector:
    app:  {{.Values.appLabel}}
  type: {{.Values.service.type}}
